apiVersion: v1
kind: Service
metadata:
  name: hellodocker-nodeport
spec:
  type: NodePort #OR LoadBalancer or ClusterIP depending on your needs
  selector:
    app: hellodocker
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080 # optional; pick any free port in 30000–32767
